     
services: 
  postgres:
    container_name: postgres_db
    image: postgres:15.1
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgresSOA
    volumes:
      - ./db_data:/var/lib/postgresql/data 
    ports:
      - 5434:5432
    restart: always
    env_file: ".env"
    networks:
      - my-red

  

  server:
    depends_on:
      - postgres
    build: .
    ports:
      - "3003:3000"
    restart: always
    environment:
      - DIALECT=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_NAME=postgresSOA
    env_file: ".env"
    networks:
      - my-red


  server2:
    depends_on:
      - postgres
    build: ./src/services/product_manage
    ports:
      - "3002:3000"
    restart: always
    environment:
      - DIALECT=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_NAME=postgresSOA
    env_file: ".env"
    networks:
      - my-red

networks:
  my-red:
    driver: bridge