     
services: 
  postgres:
    container_name: postgres_db
    image: postgres:15.1
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./db_data:/var/lib/postgresql/data 
    ports:
      - 5434:5432
    restart: always
    env_file:
      - .env

  server:
    depends_on:
      - postgres
    build: .
    ports:
      - "3003:3000"
    restart: always
    environment:
      - PORT=${PORT}
      - DIALECT=${DB_DIALECT}
    env_file:
      - .env

