     
services: 
  postgres:
    container_name: postgres_db
    image: postgres:15.1
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./db_data:/var/lib/postgresql/data 
    ports:
      - 5434:5432
    restart: always
    env_file: 
      - .env
    networks:
      - my-red

  

  server:
    depends_on:
      - postgres
    build: .
    ports:
      - "3003:3000"
    restart: always
    environment:
      - POSTGRES_PASSWORD=123456

  
  #! DIO PROBLEMAS SE DESCONECTAR EN EL DOCKER
  # pgAdmin:
  #   depends_on:
  #     - db
  #   image: dpage/pgadmin4:6.17
  #   ports:
  #     - 8081:80
  #   volumes:
  #     - ./pgAdmin:/var/lib/pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: gruposoa@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: 123456

# volumes:
#   postgres-soa:
#     external: true
      